In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.0.3'

In [5]:
df = pd.read_csv('housing.csv')

In [12]:
df[df['ocean_proximity']=="NEAR BAY"].median_house_value.mean()

259212.31179039303

In [17]:
a1 = df.total_bedrooms.mean()
print(a1)
a2 = df.total_bedrooms.fillna(a1).mean()
print(a2)
# df.total_bedrooms.mean()

537.8705525375618
537.8705525375617


In [20]:
import numpy as np
np.mean([1,2,3,4])

2.5

In [21]:
np.mean([1,2,3,4, 2.5])

2.5

In [28]:
df_small = df[df['ocean_proximity']=="ISLAND"].copy()
df_small = df_small[['housing_median_age', 'total_rooms', 'total_bedrooms']]
df_small

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [31]:
X = df_small.to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [33]:
T = X.T
T

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [40]:
XTX = np.dot(T,X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [41]:
inv = np.linalg.inv(XTX)
inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [44]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [46]:
w = np.dot(inv, np.dot(T,y))
w

array([23.12330961, -1.48124183,  5.69922946])